packages:
  - packages/*
  - playground/*
catalog:
  "@antfu/eslint-config": ^6.3.0
  "@types/node": ^24.10.1
  "@vitejs/plugin-vue": ^5.0.0
  "@wry-smile/utils": ^1.1.2
  bumpp: ^10.3.2
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  mp4box: ^2.3.0
  turbo: ^2.6.3
  typescript: ^5.9.3
  unbuild: ^3.6.1
  vite: ^7.2.6
  xgplayer: ^3.0.23
